trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  JAVA_VERSION: '21'

steps:
  # Use specific JDK version
  
  - task: JavaToolInstaller@1
    inputs:
      versionSpec: '$(JAVA_VERSION)'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  # Run Gradle build using built-in Gradle task
  - task: Gradle@3
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      tasks: 'build'
      options: '--no-daemon'
      publishJUnitResults: false
      testResultsFiles: '**/build/test-results/test/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '$(JAVA_VERSION)'
      jdkArchitectureOption: 'x64'
      sonarQubeRunAnalysis: false

  # Publish built JARs or artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'build/libs'
      artifactName: 'drop'
      publishLocation: 'Container'
