# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - master

resources:
- repo: self

variables:
  basetag: 'harnoorpuniyani/prometheus-logger-springboot:'
  buildtag: '$(Build.BuildNumber)'
  latesttag: 'latest'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'docker-harnoorpuniyani'
    #     repository: 'harnoorpuniyani/echoapp'
    #     command: 'buildAndPush'
    #     Dockerfile: '**/Dockerfile'
    #     tags: |
    #       latest
    #       $(Build.BuildNumber)
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '28.3.0'
    - script: docker buildx version
      displayName: Check docker buildx
    
    - task: Docker@2
      inputs:
        containerRegistry: 'docker-harnoorpuniyani'
        command: 'login'
        addPipelineData: false
        addBaseImageData: false
    
    - script: |
        docker buildx create --use --name builder
      displayName: create Buildx Builder

    - script: |
        docker buildx build --platform linux/amd64,linux/arm64 -t '$(basetag)$(tag)' -t '$(basetag)$(latest)' . --push
      displayName: Create and Push Multi Architecture Image