apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-test
  labels:
    app: java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      name: prometheus-test
      labels:
        app: java
    spec:
      containers:
        - name: java-pod
          image: harnoorpuniyani/prometheus-logger-springboot
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: svc-java
  labels:
    svc: java
spec:
  selector:
    app: java
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
